// Bangladesh Districts and Upazilas / Thanas — Complete list
// Organized as Record<district, upazila[]> for O(1) lookup — no performance cost

export const BD_UPAZILAS: Record<string, string[]> = {
  // ──── বরিশাল বিভাগ ────
  Barguna: ['Amtali', 'Bamna', 'Barguna Sadar', 'Betagi', 'Patharghata', 'Taltali'],
  Barisal: [
    'Agailjhara',
    'Babuganj',
    'Bakerganj',
    'Banaripara',
    'Barisal Sadar',
    'Gaurnadi',
    'Hizla',
    'Mehendiganj',
    'Muladi',
    'Wazirpur',
  ],
  Bhola: [
    'Bhola Sadar',
    'Burhanuddin',
    'Char Fasson',
    'Daulatkhan',
    'Lalmohan',
    'Manpura',
    'Tazumuddin',
  ],
  Jhalokati: ['Jhalokati Sadar', 'Kathalia', 'Nalchity', 'Rajapur'],
  Patuakhali: [
    'Bauphal',
    'Dashmina',
    'Dumki',
    'Galachipa',
    'Kalapara',
    'Mirzaganj',
    'Patuakhali Sadar',
    'Rangabali',
  ],
  Pirojpur: [
    'Bhandaria',
    'Kaukhali',
    'Mathbaria',
    'Nazirpur',
    'Nesarabad',
    'Pirojpur Sadar',
    'Zianagar',
  ],

  // ──── চট্টগ্রাম বিভাগ ────
  Bandarban: [
    'Ali Kadam',
    'Bandarban Sadar',
    'Lama',
    'Naikhongchhari',
    'Rowangchhari',
    'Ruma',
    'Thanchi',
  ],
  Brahmanbaria: [
    'Akhaura',
    'Ashuganj',
    'Bancharampur',
    'Bijoynagar',
    'Brahmanbaria Sadar',
    'Kasba',
    'Nabinagar',
    'Nasirnagar',
    'Sarail',
  ],
  Chandpur: [
    'Chandpur Sadar',
    'Faridganj',
    'Haimchar',
    'Haziganj',
    'Kachua',
    'Matlab Dakkhin',
    'Matlab Uttar',
    'Shahrasti',
  ],
  Chittagong: [
    'Anwara',
    'Banshkhali',
    'Boalkhali',
    'Chandanaish',
    'Fatikchhari',
    'Hathazari',
    'Lohagara',
    'Mirsharai',
    'Patiya',
    'Rangunia',
    'Raozan',
    'Sandwip',
    'Satkania',
    'Sitakunda',
  ],
  Comilla: [
    'Barura',
    'Brahmanpara',
    'Burichong',
    'Chandina',
    'Chauddagram',
    'Comilla Sadar',
    'Comilla Sadar South',
    'Daudkandi',
    'Debidwar',
    'Homna',
    'Laksam',
    'Meghna',
    'Monohorgonj',
    'Muradnagar',
    'Nangalkot',
    'Titas',
  ],
  "Cox's Bazar": [
    "Cox's Bazar Sadar",
    'Chakaria',
    'Kutubdia',
    'Maheshkhali',
    'Pekua',
    'Ramu',
    'Teknaf',
    'Ukhia',
  ],
  Feni: ['Chagalnaiya', 'Daganbhyan', 'Feni Sadar', 'Fhulgazi', 'Parshuram', 'Sonagazi'],
  Khagrachari: [
    'Dighinala',
    'Khagrachhari Sadar',
    'Lakshmichhari',
    'Mahalchhari',
    'Manikchhari',
    'Matiranga',
    'Panchhari',
    'Ramgarh',
  ],
  Lakshmipur: ['Kamol Nagar', 'Lakshmipur Sadar', 'Raipur', 'Ramganj', 'Ramgati'],
  Noakhali: [
    'Begumganj',
    'Chatkhil',
    'Companyganj',
    'Hatia',
    'Kobirhat',
    'Noakhali Sadar',
    'Shenbag',
    'Sonaimuri',
    'Suborno Char',
  ],
  Rangamati: [
    'Bagaichhari',
    'Barkal',
    'Belaichhari',
    'Juraichhari',
    'Kaptai',
    'Kaukhali',
    'Langadu',
    'Nannerchar',
    'Rajasthali',
    'Rangamati Sadar',
  ],

  // ──── ঢাকা বিভাগ ────
  // Dhaka city thanas (DMP) + rural upazilas — সম্পূর্ণ তালিকা
  Dhaka: [
    // City Thanas (ঢাকা মেট্রোপলিটন)
    'Adabor',
    'Airport',
    'Badda',
    'Bangshal',
    'Bimanbandar',
    'Cantonment',
    'Chawkbazar',
    'Dakshinkhan',
    'Demra',
    'Dhanmondi',
    'Gendaria',
    'Gulshan',
    'Hazaribag',
    'Jatrabari',
    'Kafrul',
    'Kalabagan',
    'Kamrangirchar',
    'Khilgaon',
    'Khilkhet',
    'Kotwali',
    'Lalbagh',
    'Mirpur',
    'Mohammadpur',
    'Motijheel',
    'Mugda',
    'New Market',
    'Pallabi',
    'Paltan',
    'Ramna',
    'Rayer Bazar',
    'Sabujbagh',
    'Shah Ali',
    'Shahjahanpur',
    'Sher-e-Bangla Nagar',
    'Shyampur',
    'Sutrapur',
    'Tejgaon',
    'Tejgaon Industrial Area',
    'Turag',
    'Uttara',
    'Uttarkhan',
    'Vatara',
    'Wari',
    // Rural Upazilas
    'Dhamrai',
    'Dohar',
    'Keraniganj',
    'Nawabganj',
    'Savar',
  ],
  Faridpur: [
    'Alfadanga',
    'Bhanga',
    'Boalmari',
    'Charbhadrasan',
    'Faridpur Sadar',
    'Madhukhali',
    'Nagarkanda',
    'Sadarpur',
    'Shaltha',
  ],
  Gazipur: ['Gazipur Sadar', 'Kaliganj', 'Kaliakior', 'Kapasia', 'Sripur', 'Tongi'],
  Gopalganj: ['Gopalganj Sadar', 'Kashiani', 'Kotalipara', 'Muksudpur', 'Tungipara'],
  Jamalpur: [
    'Baksiganj',
    'Dewanganj',
    'Islampur',
    'Jamalpur Sadar',
    'Madarganj',
    'Melandaha',
    'Sarishabari',
  ],
  Kishoreganj: [
    'Astagram',
    'Bajitpur',
    'Bhairab',
    'Hossainpur',
    'Itna',
    'Karimganj',
    'Katiadi',
    'Kishoreganj Sadar',
    'Kuliarchar',
    'Mithamain',
    'Nikli',
    'Pakundia',
    'Tarail',
  ],
  Madaripur: ['Kalkini', 'Madaripur Sadar', 'Rajoir', 'Shibchar'],
  Manikganj: [
    'Daulatpur',
    'Ghior',
    'Harirampur',
    'Manikganj Sadar',
    'Saturia',
    'Shibalaya',
    'Singair',
  ],
  Munshiganj: ['Gazaria', 'Lohajang', 'Munshiganj Sadar', 'Sirajdikhan', 'Sreenagar', 'Tongibari'],
  Mymensingh: [
    'Bhaluka',
    'Dhobaura',
    'Fulbaria',
    'Gaffargaon',
    'Gauripur',
    'Haluaghat',
    'Ishwarganj',
    'Muktagachha',
    'Mymensingh Sadar',
    'Nandail',
    'Phulpur',
    'Trishal',
  ],
  Narayanganj: ['Araihazar', 'Bandar', 'Narayanganj Sadar', 'Rupganj', 'Siddirgonj', 'Sonargaon'],
  Narsingdi: ['Belabo', 'Monohardi', 'Narsingdi Sadar', 'Palash', 'Raipura', 'Shibpur'],
  Netrokona: [
    'Atpara',
    'Barhatta',
    'Durgapur',
    'Kalmakanda',
    'Kendua',
    'Khaliajuri',
    'Madan',
    'Mohanganj',
    'Netrokona Sadar',
    'Purbadhala',
  ],
  Rajbari: ['Baliakandi', 'Goalandaghat', 'Kalukhali', 'Pangsha', 'Rajbari Sadar'],
  Shariatpur: ['Bhedarganj', 'Damudya', 'Gosairhat', 'Jajira', 'Naria', 'Shariatpur Sadar'],
  Sherpur: ['Jhenaigati', 'Nakla', 'Nalitabari', 'Sherpur Sadar', 'Sreebardi'],
  Tangail: [
    'Basail',
    'Bhuapur',
    'Delduar',
    'Dhanbari',
    'Ghatail',
    'Gopalpur',
    'Kalihati',
    'Madhupur',
    'Mirzapur',
    'Nagarpur',
    'Sakhipur',
    'Tangail Sadar',
  ],

  // ──── খুলনা বিভাগ ────
  Bagerhat: [
    'Bagerhat Sadar',
    'Chitalmari',
    'Fakirhat',
    'Kachua',
    'Mollahat',
    'Mongla',
    'Morrelganj',
    'Rampal',
    'Sarankhola',
  ],
  Chuadanga: ['Alamdanga', 'Chuadanga Sadar', 'Damurhuda', 'Jibannagar'],
  Jessore: [
    'Abhaynagar',
    'Bagherpara',
    'Chaugachha',
    'Jessore Sadar',
    'Jhikargachha',
    'Keshabpur',
    'Manirampur',
    'Sharsha',
  ],
  Jhenaidah: [
    'Harinakunda',
    'Jhenaidah Sadar',
    'Kaliganj',
    'Kotchandpur',
    'Maheshpur',
    'Shailkupa',
  ],
  Khulna: [
    'Batiaghata',
    'Dacope',
    'Dighalia',
    'Dumuria',
    'Koyra',
    'Paikgachha',
    'Phultala',
    'Rupsa',
    'Terokhada',
  ],
  Kushtia: ['Bheramara', 'Daulatpur', 'Khoksa', 'Kumarkhali', 'Kushtia Sadar', 'Mirpur'],
  Magura: ['Magura Sadar', 'Mohammadpur', 'Shalikha', 'Sreepur'],
  Meherpur: ['Gangni', 'Meherpur Sadar', 'Mujib Nagar'],
  Narail: ['Kalia', 'Lohagara', 'Narail Sadar'],
  Satkhira: ['Assasuni', 'Debhata', 'Kalaroa', 'Kaliganj', 'Satkhira Sadar', 'Shyamnagar', 'Tala'],

  // ──── রাজশাহী বিভাগ ────
  Bogra: [
    'Adamdighi',
    'Bogra Sadar',
    'Dhunat',
    'Dhupchanchia',
    'Gabtali',
    'Kahaloo',
    'Nandigram',
    'Sahajanpur',
    'Sariakandi',
    'Sherpur',
    'Shibganj',
    'Sonatala',
  ],
  Joypurhat: ['Akkelpur', 'Joypurhat Sadar', 'Kalai', 'Khetlal', 'Panchbibi'],
  Naogaon: [
    'Atrai',
    'Badalgachhi',
    'Dhamoirhat',
    'Manda',
    'Mohadevpur',
    'Naogaon Sadar',
    'Niamatpur',
    'Patnitala',
    'Porsha',
    'Raninagar',
    'Sapahar',
  ],
  Natore: ['Bagatipara', 'Baraigram', 'Lalpur', 'Natore Sadar', 'Singra'],
  Nawabganj: ['Bholahat', 'Gomastapur', 'Nachole', 'Nawabganj Sadar', 'Shibganj'],
  Pabna: [
    'Atgharia',
    'Bera',
    'Bhangura',
    'Chatmohar',
    'Faridpur',
    'Ishwardi',
    'Pabna Sadar',
    'Santhia',
    'Sujanagar',
  ],
  Rajshahi: [
    'Bagha',
    'Bagmara',
    'Charghat',
    'Durgapur',
    'Godagari',
    'Mohanpur',
    'Paba',
    'Puthia',
    'Tanore',
  ],
  Sirajganj: [
    'Belkuchi',
    'Chauhali',
    'Kamarkhanda',
    'Kazipur',
    'Raiganj',
    'Shahjadpur',
    'Sirajganj Sadar',
    'Tarash',
    'Ullahpara',
  ],

  // ──── রংপুর বিভাগ ────
  Dinajpur: [
    'Birampur',
    'Birganj',
    'Biral',
    'Bochaganj',
    'Chirirbandar',
    'Dinajpur Sadar',
    'Ghoraghat',
    'Hakimpur',
    'Kaharole',
    'Khansama',
    'Nawabganj',
    'Parbatipur',
    'Phulbari',
  ],
  Gaibandha: [
    'Fulchhari',
    'Gaibandha Sadar',
    'Gobindaganj',
    'Palashbari',
    'Sadullapur',
    'Saghata',
    'Sundarganj',
  ],
  Kurigram: [
    'Bhurungamari',
    'Char Rajibpur',
    'Chilmari',
    'Kurigram Sadar',
    'Nageshwari',
    'Phulbari',
    'Rajarhat',
    'Rowmari',
    'Ulipur',
  ],
  Lalmonirhat: ['Aditmari', 'Hatibandha', 'Kaliganj', 'Lalmonirhat Sadar', 'Patgram'],
  Nilphamari: ['Dimla', 'Domar', 'Jaldhaka', 'Kishoreganj', 'Nilphamari Sadar', 'Saidpur'],
  Panchagarh: ['Atwari', 'Boda', 'Debiganj', 'Panchagarh Sadar', 'Tetulia'],
  Rangpur: [
    'Badarganj',
    'Gangachara',
    'Kaunia',
    'Mithapukur',
    'Pirgachha',
    'Pirganj',
    'Rangpur Sadar',
    'Taraganj',
  ],
  Thakurgaon: ['Baliadangi', 'Haripur', 'Pirganj', 'Ranisankail', 'Thakurgaon Sadar'],

  // ──── সিলেট বিভাগ ────
  Habiganj: [
    'Ajmiriganj',
    'Bahubal',
    'Baniachang',
    'Chunarughat',
    'Habiganj Sadar',
    'Lakhai',
    'Madhabpur',
    'Nabiganj',
    'Shaistagonj',
  ],
  Maulvibazar: [
    'Barlekha',
    'Juri',
    'Kamalganj',
    'Kulaura',
    'Moulvibazar Sadar',
    'Rajnagar',
    'Sreemangal',
  ],
  Sunamganj: [
    'Bishwamvarpur',
    'Chhatak',
    'Derai',
    'Dharampasha',
    'Dowarabazar',
    'Jagannathpur',
    'Jamalganj',
    'Shanthiganj',
    'Sulla',
    'Sunamganj Sadar',
    'Tahirpur',
  ],
  Sylhet: [
    'Balaganj',
    'Beanibazar',
    'Bishwanath',
    'Companiganj',
    'Dakshin Surma',
    'Fenchuganj',
    'Golapganj',
    'Gowainghat',
    'Jaintiapur',
    'Kanaighat',
    'Nobigonj',
    'Sylhet Sadar',
    'Zakiganj',
  ],
};

// Sorted district list
export const BD_DISTRICTS = Object.keys(BD_UPAZILAS).sort((a, b) => a.localeCompare(b));

// Get upazilas for a district (returns empty array if not found)
export function getUpazilas(district: string): string[] {
  return BD_UPAZILAS[district] ?? [];
}
